### ISSUE TITLE
aks deployment via terraform script

### ISSUE THREAD

**Issue by Premkumar-Mani-NTT** [RafaySystems/getstarted#40]
I am trying to deploy the aks cluster using the terraform script into rafay and getting the below error that

│ Error: failed to create/update cluster while provisioning cluster aks-cluster {"taskset_id":"5m1pprm","operations":[{"operation":"ClusterCreation","resource_name":"aks-cluster","status":"PROVISION_TASK_STATUS_FAILED","error":{"title":"Error while creating cluster infrastructure: error while creating deployment, resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code=\"ResourceGroupNotFound\" Message=\"Resource group 'aks-rg-clut' could not be found.\""}},{"operation":"NodegroupCreation","resource_name":"pool1","status":"PROVISION_TASK_STATUS_PENDING"},{"operation":"BlueprintSync","resource_name":"aks-cluster","status":"PROVISION_TASK_STATUS_PENDING"}],"comments":"There were problem(s) while applying configuration to the cluster","status":"PROVISION_TASKSET_STATUS_FAILED"}
│ 
│ 
│   with module.cluster.rafay_aks_cluster.cluster,
│   on modules/aks/main.tf line 7, in resource "rafay_aks_cluster" "cluster":
│    7: resource "rafay_aks_cluster" "cluster" {

do we need to create rg , however inside the module of aks i don't find option to create RG, can you please advise on the error?

**Comment by hardik-rafay** [comment]
@premnttdata With the current implementation of the AKS module, the resouce group is part of the prerequisite so the module expects that resource-group is already created outside of this module. 

Let us know if you have any other questions.
